### PR TITLE
update to docker and simplification of opening docker

### PR DESCRIPTION
**Pull request by CarolineMorton**
Hi Nick, 

I have added the docker files and changed the paths as discussed. 

Please have a look and check this works. 

This [link](https://github.com/ebmdatalab/custom-docker/tree/seb-docker-windows-improvements) has the instructions for getting docker up and running. I would suggest that you attempt this on this branch before you pull into master. 

if you go to command line, navigate into fdaaa trends and do:
``git checkout docker-config``

once you have that, if you download Docker (if on your windows) or make sure docker running (if on your mac). if you are using mac, then run ``sh run.sh``, on windows double click the run.in

### CODE REVIEW

**Comment by NickCEBM** [comment]
@sebbacon Should there be more commits here? Looks like none showed up from the other day.

**Comment by NickCEBM** [comment]
Is this ready to go or is there more to update?

**Comment by sebbacon** [comment]
Happy to merge. At some point (part of this PR or a different one) you should update the README with basic pointers to running it for 3rd parties, i.e. the relevant bits of the README from `custom-docker` repo. Including the badge showing that the tests are green!

**Comment by NickCEBM** [comment]
Great. Yes, I'll treat updating the documentation as it's own little project once we're sure this is all working.

**Pull request merged**
